name: Run Tests

on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
    types: [opened, synchronize, reopened]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache Python packages
        uses: actions/cache@v4
        with:
          path: ~/.local/lib/python3.12/site-packages
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  test_common:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run common tests
        env:
          NOVA_POST_API_KEY: ${{ secrets.NOVA_POST_API_KEY }}
        run: pytest tests/test_common.py

  test_tracking:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run tracking tests
        env:
          NOVA_POST_API_KEY: ${{ secrets.NOVA_POST_API_KEY }}
          NOVA_POST_TRACKING_NUMBER: ${{ secrets.NOVA_POST_TRACKING_NUMBER }}
        run: pytest tests/test_tracking.py

  test_address:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run address tests
        env:
          NOVA_POST_API_KEY: ${{ secrets.NOVA_POST_API_KEY }}
        run: pytest tests/test_address.py

  test_counterparty:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run counterparty tests
        env:
          NOVA_POST_API_KEY: ${{ secrets.NOVA_POST_API_KEY }}
        run: pytest tests/test_counterparty.py